// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using jbH60Store.Models;

#nullable disable

namespace jbH60Store.Migrations
{
    [DbContext(typeof(H60AssignmentDB_jbContext))]
    [Migration("20231103005525_initialDB2")]
    partial class initialDB2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("jbH60Store.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"), 1L, 1);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            CartItemId = 1,
                            CartId = 1,
                            Price = 40m,
                            ProductId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            CartItemId = 2,
                            CartId = 1,
                            Price = 20m,
                            ProductId = 8,
                            Quantity = 2
                        },
                        new
                        {
                            CartItemId = 3,
                            CartId = 1,
                            Price = 25m,
                            ProductId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            CartItemId = 4,
                            CartId = 2,
                            Price = 49m,
                            ProductId = 15,
                            Quantity = 2
                        },
                        new
                        {
                            CartItemId = 5,
                            CartId = 2,
                            Price = 22m,
                            ProductId = 17,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("jbH60Store.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<string>("CreditCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CreditCard = "4519 4383 3829 4738",
                            Email = "joelle.cunningham@gmail.com",
                            FirstName = "Joelle",
                            LastName = "Cunningham",
                            PhoneNumber = "613-478-4783",
                            Province = "ON"
                        },
                        new
                        {
                            CustomerId = 2,
                            CreditCard = "4378 4367 2143 0329",
                            Email = "brandie.lucas@yahoo.com",
                            FirstName = "Brandie",
                            LastName = "Lucas",
                            PhoneNumber = "819-478-3923",
                            Province = "QC"
                        },
                        new
                        {
                            CustomerId = 3,
                            CreditCard = "3267 2173 4398 4388",
                            Email = "t.pena@outlook.com",
                            FirstName = "Troy",
                            LastName = "Pena",
                            PhoneNumber = "825-372-1273",
                            Province = "AB"
                        });
                });

            modelBuilder.Entity("jbH60Store.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFufilled")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            DateCreated = new DateTime(2023, 10, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            DateFufilled = new DateTime(2023, 10, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Taxes = 12.88m,
                            Total = 86m
                        });
                });

            modelBuilder.Entity("jbH60Store.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"), 1L, 1);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            OrderItemId = 1,
                            OrderId = 1,
                            Price = 40m,
                            ProductId = 5,
                            Quantity = 1
                        },
                        new
                        {
                            OrderItemId = 2,
                            OrderId = 1,
                            Price = 20m,
                            ProductId = 8,
                            Quantity = 2
                        },
                        new
                        {
                            OrderItemId = 3,
                            OrderId = 1,
                            Price = 25m,
                            ProductId = 4,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("jbH60Store.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<decimal?>("BuyPrice")
                        .IsRequired()
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("EmployeeNotes")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("EmployeeNotes");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("ProdCatId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SellPrice")
                        .HasColumnType("numeric(8,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex(new[] { "ProdCatId" }, "IX_Product_ProdCatId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            BuyPrice = 10m,
                            Description = "Radiant Glow Serum",
                            Manufacturer = "Lux Beauty",
                            ProdCatId = 1,
                            SellPrice = 25m,
                            Stock = 100
                        },
                        new
                        {
                            ProductId = 2,
                            BuyPrice = 12m,
                            Description = "Hyaluronic Acid Moisturizer",
                            Manufacturer = "Pure Essentials",
                            ProdCatId = 1,
                            SellPrice = 28m,
                            Stock = 200
                        },
                        new
                        {
                            ProductId = 3,
                            BuyPrice = 9m,
                            Description = "Charcoal Detoxifying Mask",
                            EmployeeNotes = "Newly added product",
                            Manufacturer = "Zen Skin Solutions",
                            ProdCatId = 1,
                            SellPrice = 22m,
                            Stock = 130
                        },
                        new
                        {
                            ProductId = 4,
                            BuyPrice = 8m,
                            Description = "Vitamin C Brightening Toner",
                            Manufacturer = "GlowBunny Cosmetics",
                            ProdCatId = 1,
                            SellPrice = 25m,
                            Stock = 180
                        },
                        new
                        {
                            ProductId = 5,
                            BuyPrice = 15m,
                            Description = "Midnight Orchid Eau de Parfum",
                            Manufacturer = "Lux Beauty",
                            ProdCatId = 3,
                            SellPrice = 40m,
                            Stock = 75
                        },
                        new
                        {
                            ProductId = 6,
                            BuyPrice = 5m,
                            Description = "Velvet Matte Lipstick",
                            EmployeeNotes = "Best Selling Product!",
                            Manufacturer = "Lux Beauty",
                            ProdCatId = 4,
                            SellPrice = 15m,
                            Stock = 120
                        },
                        new
                        {
                            ProductId = 7,
                            BuyPrice = 25m,
                            Description = "Jade Roller and Gua Sha Set",
                            Manufacturer = "Zen Skin Solutions",
                            ProdCatId = 5,
                            SellPrice = 56m,
                            Stock = 160
                        },
                        new
                        {
                            ProductId = 8,
                            BuyPrice = 7m,
                            Description = "HD Foundation Primer",
                            Manufacturer = "Pure Essentials",
                            ProdCatId = 4,
                            SellPrice = 20m,
                            Stock = 150
                        },
                        new
                        {
                            ProductId = 9,
                            BuyPrice = 13m,
                            Description = "Metallic Eyeshadow Palette",
                            Manufacturer = "GlowBunny Cosmetics",
                            ProdCatId = 4,
                            SellPrice = 32m,
                            Stock = 110
                        },
                        new
                        {
                            ProductId = 10,
                            BuyPrice = 16m,
                            Description = "Vanilla Spice Perfume Oil",
                            Manufacturer = "GlowBunny Cosmetics",
                            ProdCatId = 3,
                            SellPrice = 38m,
                            Stock = 0
                        },
                        new
                        {
                            ProductId = 11,
                            BuyPrice = 14m,
                            Description = "Ocean Breeze Body Mist",
                            Manufacturer = "Zen Skin Solutions",
                            ProdCatId = 3,
                            SellPrice = 32m,
                            Stock = 80
                        },
                        new
                        {
                            ProductId = 12,
                            BuyPrice = 6m,
                            Description = "Waterproof Mascara",
                            Manufacturer = "Zen Skin Solutions",
                            ProdCatId = 4,
                            SellPrice = 18m,
                            Stock = 140
                        },
                        new
                        {
                            ProductId = 13,
                            BuyPrice = 18m,
                            Description = "Citrus Sunshine Cologne",
                            Manufacturer = "Pure Essentials",
                            ProdCatId = 3,
                            SellPrice = 45m,
                            Stock = 92
                        },
                        new
                        {
                            ProductId = 14,
                            BuyPrice = 125m,
                            Description = "Ionic Hair Straightener",
                            Manufacturer = "Pure Essentials",
                            ProdCatId = 5,
                            SellPrice = 300m,
                            Stock = 90
                        },
                        new
                        {
                            ProductId = 15,
                            BuyPrice = 24m,
                            Description = "Professional Makeup Brush Set",
                            Manufacturer = "Lux Beauty",
                            ProdCatId = 5,
                            SellPrice = 49m,
                            Stock = 50
                        },
                        new
                        {
                            ProductId = 16,
                            BuyPrice = 7m,
                            Description = "Precision Tweezers",
                            Manufacturer = "Lux Beauty",
                            ProdCatId = 5,
                            SellPrice = 15m,
                            Stock = 75
                        },
                        new
                        {
                            ProductId = 17,
                            BuyPrice = 9m,
                            Description = "Keratin Hair Mask",
                            Manufacturer = "Zen Skin Solutions",
                            ProdCatId = 2,
                            SellPrice = 22m,
                            Stock = 160
                        },
                        new
                        {
                            ProductId = 18,
                            BuyPrice = 10m,
                            Description = "Coconut Milk Conditioner",
                            Manufacturer = "Pure Essentials",
                            ProdCatId = 2,
                            SellPrice = 24m,
                            Stock = 180
                        },
                        new
                        {
                            ProductId = 19,
                            BuyPrice = 8m,
                            Description = "Argan Oil Shampoo",
                            Manufacturer = "Lux Beauty",
                            ProdCatId = 2,
                            SellPrice = 20m,
                            Stock = 150
                        },
                        new
                        {
                            ProductId = 20,
                            BuyPrice = 8m,
                            Description = "Glow Bomb",
                            Manufacturer = "GlowBunny Cosmetics",
                            ProdCatId = 4,
                            SellPrice = 20m,
                            Stock = 0
                        },
                        new
                        {
                            ProductId = 21,
                            BuyPrice = 10m,
                            Description = "Curl Defining Cream",
                            Manufacturer = "GlowBunny Cosmetics",
                            ProdCatId = 2,
                            SellPrice = 26m,
                            Stock = 130
                        });
                });

            modelBuilder.Entity("jbH60Store.Models.ProductCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("ProdCat")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.HasKey("CategoryId");

                    b.ToTable("ProductCategory", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            ProdCat = "Skin Care"
                        },
                        new
                        {
                            CategoryId = 2,
                            ProdCat = "Hair Care"
                        },
                        new
                        {
                            CategoryId = 3,
                            ProdCat = "Fragrances"
                        },
                        new
                        {
                            CategoryId = 4,
                            ProdCat = "Makeup"
                        },
                        new
                        {
                            CategoryId = 5,
                            ProdCat = "Tools and Brushes"
                        });
                });

            modelBuilder.Entity("jbH60Store.Models.ShoppingCart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("CartId");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("ShoppingCarts");

                    b.HasData(
                        new
                        {
                            CartId = 1,
                            CustomerId = 1,
                            DateCreated = new DateTime(2023, 10, 23, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            CartId = 2,
                            CustomerId = 2,
                            DateCreated = new DateTime(2023, 10, 28, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("jbH60Store.Models.CartItem", b =>
                {
                    b.HasOne("jbH60Store.Models.ShoppingCart", "ShoppingCart")
                        .WithMany("CartItem")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CartItem_ShoppingCart_CartId");

                    b.HasOne("jbH60Store.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("jbH60Store.Models.Order", b =>
                {
                    b.HasOne("jbH60Store.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("jbH60Store.Models.OrderItem", b =>
                {
                    b.HasOne("jbH60Store.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("jbH60Store.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("jbH60Store.Models.Product", b =>
                {
                    b.HasOne("jbH60Store.Models.ProductCategory", "ProdCat")
                        .WithMany("Products")
                        .HasForeignKey("ProdCatId")
                        .IsRequired()
                        .HasConstraintName("FK_Product_ProductCategory");

                    b.Navigation("ProdCat");
                });

            modelBuilder.Entity("jbH60Store.Models.ShoppingCart", b =>
                {
                    b.HasOne("jbH60Store.Models.Customer", "Customer")
                        .WithOne("ShoppingCarts")
                        .HasForeignKey("jbH60Store.Models.ShoppingCart", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("jbH60Store.Models.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("ShoppingCarts")
                        .IsRequired();
                });

            modelBuilder.Entity("jbH60Store.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("jbH60Store.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("jbH60Store.Models.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("jbH60Store.Models.ShoppingCart", b =>
                {
                    b.Navigation("CartItem");
                });
#pragma warning restore 612, 618
        }
    }
}
